//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Water_Batch_UniqueSym.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class IRgbColorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static IRgbColorSettings defaultInstance = ((IRgbColorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IRgbColorSettings())));
        
        public static IRgbColorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color FromColor {
            get {
                return ((global::System.Drawing.Color)(this["FromColor"]));
            }
            set {
                this["FromColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ToColor {
            get {
                return ((global::System.Drawing.Color)(this["ToColor"]));
            }
            set {
                this["ToColor"] = value;
            }
        }
    }
}
